// A realistic, fully-populated profile — one click in Settings ("Load demo
// data") fills the SIGNED-IN account so the app can be clicked through or
// demoed without hand-typing a whole profile first. Not shared/seeded data:
// each call writes into that one account's own row, same as any other edit.
import type { Student } from "./types";
import { uid } from "./seed";

export function demoStudentFields(): Omit<Student, "id" | "role" | "onboarded"> {
  return {
    name: "Jordan Reyes",
    title: "",
    grad: "2027",
    majors: ["Environmental Studies"],
    minors: ["Data Science"],
    interests: ["Sustainability", "Photography", "Hiking"],
    headline: "Aiming for a policy or sustainability-focused role after graduation",
    resumeUrl: "",
    linkedin: "linkedin.com/in/jordanreyes",
    avatarUrl: "",
    outreachStatus: "not-contacted",
    skills: [
      {
        id: uid(),
        title: "Data Analysis",
        path: "data-tech-cs",
        evidence: [
          { id: uid(), date: "2025-06-20", description: "Analyzed campaign metrics as a Marketing Intern at Patagonia" },
          { id: uid(), date: "2026-02-10", description: "Built datasets for an environmental research project" },
        ],
      },
      {
        id: uid(),
        title: "Python",
        path: "data-tech-cs",
        evidence: [
          { id: uid(), date: "2026-01-25", description: "Used for data cleaning in the Environmental Studies Lab" },
          { id: uid(), date: "2026-03-15", description: "Automated a repetitive data-entry script" },
          { id: uid(), date: "2026-05-05", description: "Coursework project analyzing climate data" },
        ],
      },
      {
        id: uid(),
        title: "Public Speaking",
        path: "public-service-law-policy",
        evidence: [
          { id: uid(), date: "2024-10-10", description: "Ran weekly meetings as Program Coordinator for Students for Environmental Action" },
        ],
      },
      {
        id: uid(),
        title: "Policy Research",
        path: "public-service-law-policy",
        evidence: [
          { id: uid(), date: "2024-09-20", description: "Started volunteering on environmental policy at the OAKS Center" },
        ],
      },
    ],
    entries: [
      {
        id: uid(),
        title: "Research Assistant",
        category: "research",
        organization: "Environmental Studies Lab, L&C",
        location: "Portland, OR",
        meta: "",
        startDate: "2026-01-12",
        ongoing: true,
        path: "environment-sustainability-science",
        tools: ["Data Analysis", "Research Methods", "Python", "Statistics"],
      },
      {
        id: uid(),
        title: "Marketing Intern",
        category: "internship",
        organization: "Patagonia Portland",
        location: "Portland, OR",
        meta: "",
        startDate: "2025-06-02",
        endDate: "2025-08-22",
        ongoing: false,
        path: "comm-marketing-pr",
        tools: ["Marketing", "Data Analysis", "Communication", "Social Media"],
      },
      {
        id: uid(),
        title: "Program Coordinator",
        category: "leadership",
        organization: "Students for Environmental Action",
        location: "Lewis & Clark College",
        meta: "",
        startDate: "2024-09-05",
        ongoing: true,
        path: "environment-sustainability-science",
        tools: ["Leadership", "Event Planning", "Public Speaking", "Budgeting"],
      },
      {
        id: uid(),
        title: "Environmental Policy Volunteer",
        category: "volunteer",
        organization: "OAKS Center",
        location: "Portland, OR",
        meta: "",
        startDate: "2024-09-10",
        ongoing: true,
        path: "public-service-law-policy",
        tools: ["Policy Research", "Community Outreach", "Writing"],
        hoursLogged: 45,
      },
      {
        id: uid(),
        title: "Semester Abroad",
        category: "study-abroad",
        organization: "Copenhagen Business School",
        location: "Copenhagen, Denmark",
        meta: "",
        startDate: "2025-01-15",
        endDate: "2025-05-20",
        ongoing: false,
        path: "global-diplomacy-languages",
        tools: ["Cross-cultural Communication", "Sustainability", "Adaptability"],
      },
      {
        id: uid(),
        title: "Resident Assistant",
        category: "campus-involvement",
        organization: "Lewis & Clark Residential Life",
        location: "Portland, OR",
        meta: "",
        startDate: "2025-08-15",
        ongoing: true,
        path: "",
        tools: ["Counseling", "Community Building", "Crisis Management", "Leadership"],
      },
    ],
    contacts: [
      {
        id: uid(),
        name: "Sarah Chen",
        relationship: "alumni",
        path: "environment-sustainability-science",
        company: "Nike Inc.",
        role: "Sustainability Manager",
        grad: "2018",
        strength: 3,
        email: "sarah.chen@example.com",
        linkedin: "linkedin.com/in/sarahchen",
        note: "",
        date: "2026-07-15",
      },
      {
        id: uid(),
        name: "Dr. James Rivera",
        relationship: "faculty",
        path: "public-service-law-policy",
        company: "Lewis & Clark College",
        role: "Professor of Political Science",
        strength: 3,
        email: "jrivera@example.edu",
        note: "",
        date: "2026-07-22",
      },
      {
        id: uid(),
        name: "Marcus Williams",
        relationship: "recruiter",
        path: "",
        company: "Deloitte",
        role: "Campus Recruiter",
        strength: 2,
        email: "marcus.williams@example.com",
        linkedin: "linkedin.com/in/marcuswilliams",
        note: "",
        date: "2026-06-29",
      },
      {
        id: uid(),
        name: "Priya Patel",
        relationship: "alumni",
        path: "data-tech-cs",
        company: "Salesforce",
        role: "Product Manager",
        grad: "2020",
        strength: 2,
        email: "priya.patel@example.com",
        linkedin: "linkedin.com/in/priyapatel",
        note: "",
        date: "2026-04-29",
      },
      {
        id: uid(),
        name: "Dr. Amara Osei",
        relationship: "mentor",
        path: "environment-sustainability-science",
        company: "Oregon Environmental Council",
        role: "Executive Director",
        strength: 3,
        email: "aosei@example.org",
        note: "",
        date: "2026-07-08",
      },
      {
        id: uid(),
        name: "Kai Tanaka",
        relationship: "other",
        path: "public-service-law-policy",
        company: "City of Portland",
        role: "Policy Analyst",
        strength: 1,
        linkedin: "linkedin.com/in/kaitanaka",
        note: "",
        date: "2026-05-29",
      },
    ],
    applications: [
      {
        id: uid(),
        company: "Oregon Environmental Council",
        role: "Policy Fellow (Summer)",
        link: "",
        source: "external",
        deadline: "2026-08-15",
        status: "interviewing",
        notes: "Referred by Dr. Amara Osei",
        date: "2026-06-01",
      },
      {
        id: uid(),
        company: "City of Portland",
        role: "Sustainability Analyst Intern",
        link: "",
        source: "external",
        deadline: "2026-09-01",
        status: "applied",
        notes: "",
        date: "2026-07-10",
      },
      {
        id: uid(),
        company: "Deloitte",
        role: "Sustainability Consulting Intern",
        link: "",
        source: "external",
        deadline: "",
        status: "saved",
        notes: "Recruiter contact: Marcus Williams",
        date: "2026-07-20",
      },
    ],
    eventsAttended: ["e5", "e6"],
    advisingNotes: [
      {
        id: uid(),
        date: "2026-07-15",
        note: "Great momentum on the sustainability track — consider connecting with the Career Center's environmental industry panel next month.",
      },
    ],
    todos: [{ id: uid(), text: "Follow up with Oregon Environmental Council after the interview", done: false, date: "2026-07-25" }],
    dismissedSuggestions: [],
  };
}
