let _id = 100;
export const uid = (): string =>
  (++_id).toString(36) + Date.now().toString(36).slice(-3);

// Real Lewis & Clark College undergraduate programs (college.lclark.edu/academics/majors-and-minors/).
export const MAJORS = [
  "Art (Studio)",
  "Art History",
  "Biochemistry and Molecular Biology",
  "Biology",
  "Chemistry",
  "Classics",
  "Computer Science",
  "Computer Science and Mathematics",
  "Data Science",
  "Economics",
  "English",
  "Environmental Studies",
  "French Studies",
  "German Studies",
  "Hispanic Studies",
  "History",
  "International Affairs",
  "Mathematics and Statistics",
  "Music",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Religious Studies",
  "Rhetoric and Media Studies",
  "Sociology and Anthropology",
  "Student-Designed Major",
  "Theatre",
  "World Languages",
];

export const MINORS = [
  "Art and Art History",
  "Artificial Intelligence",
  "Asian Studies",
  "Chemistry",
  "Chinese",
  "Classics",
  "Computer Science",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Earth System Science",
  "Economics",
  "Education",
  "English",
  "Entrepreneurial Leadership and Innovation",
  "Environmental Studies",
  "Ethnic Studies",
  "French Studies",
  "Gender Studies",
  "German Studies",
  "Health Studies",
  "Hispanic Studies",
  "History",
  "Japanese",
  "Latin American and Latino Studies",
  "Law and Policy",
  "Mathematics and Statistics",
  "Middle East and North African Studies",
  "Music",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Political Economy",
  "Political Science",
  "Religious Studies",
  "Rhetoric and Media Studies",
  "Russian",
  "Theatre",
];
